set(CMAKE_SYSTEM_NAME Amiga)

set(CMAKE_C_COMPILER   m68k-amigaos-gcc)
set(CMAKE_CXX_COMPILER m68k-amigaos-g++)

SET(CMAKE_C_FLAGS   "-O2 -g -noixemul -m68060 --omit-frame-pointer")
SET(CMAKE_CXX_FLAGS "-O2 -g -noixemul -m68060 --omit-frame-pointer")

set(CMAKE_FIND_ROOT_PATH  /opt/amiga)

#set(CMAKE_C_COMPILER_WORKS TRUE CACHE INTERNAL "")
#set(CMAKE_CXX_COMPILER_WORKS TRUE CACHE INTERNAL "")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)

set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
